### ISSUE TITLE
rmt_neopixel.rs example doesn't work on ESP32-C3-DevKitC-02 when used in esp32-idf-template

### ISSUE THREAD

**Issue by mattlinskys** [esp-rs/esp-idf-hal#429]
When I run rmt neopixel example https://github.com/esp-rs/esp-idf-hal/blob/master/examples/rmt_neopixel.rs on my ESP32-C3-DevKitC-02 LED everything works just line.

On the other hand when I copy code from `rmt_neopixel.rs` to `main.rs` of project generated with `esp32-idf-template` then program itself runs but LED doesn't light up. Here's my repo that doesn't work https://github.com/mattlinskys/esp32c3-led-test

Is there anything that I'm missing with configuration? It looks like esp32-idf-sys and esp32-idf-hal have the same versions

**Comment by Vollbrecht** [comment]
Your configuration per se is fine. The current release of esp-idf-hal has a problem with the rmt device. That was already fixed in the master branch. That's why it is working for you, If you create a new template and want to use the rmt device please patch the esp-idf-* deps to the current master branch.

You can do so by adding the following to your Cargo.toml
```toml
[patch.crates-io]
embuild = { git = "https://github.com/esp-rs/embuild" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
embedded-svc = { git = "https://github.com/esp-rs/embedded-svc" }
```
and run `cargo update` so the git deps are correctly fetched, followed by a `cargo clean & cargo build` 

We hope that we can get shortly a release out so out but are still not 100% there. Sorry for the trouble !
