### ISSUE TITLE
SPI no longer works after update from `v0.30 -> v0.37`

### ISSUE THREAD

**Issue by akselbor** [esp-rs/esp-idf-hal#79]
I've been using an ESP32-S3 to control a couple of [TMC5160s](https://www.trinamic.com/products/integrated-circuits/details/tmc5160/)  over SPI using `esp-idf-hal v0.30`. Yesterday, I updated the project to `esp-idf-hal v0.37` and found that the SPI communication no longer works. The code is unchanged between `v0.30` and `v0.37`, except for the necessary changes to `spi::config::Config` during initialization.

Any idea what might be causing this? I would guess that it is related to 2d0554d9878391521cf56a03607e3b6a7158f4b4? I'll try to debug the issue by myself in the meantime.

The relevant section of code looks roughly like this, after the abstractions have been removed:
```rust
// Note: spi_pins.cs == None
let spi_pins = ...
let mut cs = ...

let spi = Master::<SPI2, _, _, _, _>::new(
        peripherals.spi2,
        spi_pins,
        esp_idf_hal::spi::config::Config {
            baudrate: Hertz(4_000_000),
            data_mode: embedded_hal::spi::MODE_3,                    // v0.37: V02Type(MODE_3).into()
            bit_order: esp_idf_hal::spi::config::BitOrder::MSBFirst, // v0.37: Removed
        },
    )?;
    
// Note: config::BitOrder should (?) be irrelevant, since I construct the bytes myself. As far as I could see from spi.rs
// the BitOrder only affects the ordering of the bytes (weirdly enough) when using Word::load/store for u16, u32.
let data: &mut [[u8; 5]] = ...
for datagram in data {
    cs.set_low()?;
    spi.transfer(&mut datagram)?;
    cs.set_high()?;
}
```

Versions used:
```toml
# Old
esp-idf-sys = { version = "0.28.3", features = ["binstart"] }
embedded-svc = "0.15.4"
esp-idf-svc = "0.34.3"
esp-idf-hal = "0.30.0"
embedded-hal = "0.2"

# New
esp-idf-sys = { version = "0.31", features = ["binstart"] }
embedded-svc = "0.21"
esp-idf-svc = "0.41"
esp-idf-hal = "0.37"
embedded-hal = "0.2"

# Common
ESP_IDF_VERSION = { value = "release/v4.4" } 
```
